apiVersion: v1
kind: ConfigMap
metadata: 
  name: emp-friendly-cm
  namespace: emp-friendly
data:
  # Topic
  RECEIVED_RATING_TOPIC_NAME: 'received-rating-topic'
  INVOICE_CREATE_TOPIC_NAME: 'invoice-create-topic'
  NOTIFICATION_SENT_TOPIC_NAME: 'notification-sent-topic'
  SHIPMENT_TOPIC_NAME: 'shipment-topic'
  LOCATION_STREAM_EVENT_NAME: 'location-stream-event'
  START_DRIVE_TOPIC_NAME: 'start-drive-topic'
  PAYMENT_COMPLETED_TOPIC_NAME: 'payment-completed-topic'
  PAYMENT_ERROR_TOPIC_NAME: 'payment-error-topic'
  CREATE_NEW_RESTAURANT_TOPIC_NAME: 'create-new-restaurant-topic'
  # Other
  PAYMENT_URL_FOR_QR: '/payments/{id}'
  PAYMENT_RESTAURANT_URL_FOR_QR: '/payments/restaurants/{id}'
  # URL
  EMPLOYEE_SERVICE_URL: emp-friendly-employee.emp-friendly.svc.cluster.local:50203
  LOCATION_SERVICE_URL: emp-friendly-location.emp-friendly.svc.cluster.local:50204
  POINT_SERVICE_URL: emp-friendly-point.emp-friendly.svc.cluster.local:50205
  ORDER_SERVICE_URL: emp-friendly-order.emp-friendly.svc.cluster.local:50206
  PAYMENT_SERVICE_URL: emp-friendly-payment.emp-friendly.svc.cluster.local:50207
  QR_SERVICE_URL: emp-friendly-qr-service.emp-friendly.svc.cluster.local:50208
  RATING_SERVICE_URL: emp-friendly-rating.emp-friendly.svc.cluster.local:50209
  RESTAURANT_MANAGEMENT_SERVICE_URL: emp-friendly-rest-mgm.emp-friendly.svc.cluster.local:50210
