apiVersion: apps/v1
kind: Deployment
metadata:
  name: emp-friendly-invoice
  namespace: emp-friendly
  labels:
    field.cattle.io/projectId: p-82znb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emp-friendly-invoice
  template:
    metadata:
      labels:
        app: emp-friendly-invoice
    spec:
      containers:
        - name: emp-friendly-invoice
          image: marttp/emp-friendly-invoice
          resources:
            requests:
              cpu: 300m
              memory: 512Mi
            limits:
              cpu: 300m
              memory: 512Mi
          ports:
            - containerPort: 8000
              name: invoice
              protocol: TCP
          env:
            - name: INVOICE_CREATE_TOPIC_NAME
              valueFrom:
                configMapKeyRef:
                  name: emp-friendly-cm
                  key: INVOICE_CREATE_TOPIC_NAME
            - name: REDIS_OM_URL
              valueFrom:
                secretKeyRef:
                  name: redis-secrect
                  key: REDIS_OM_URL
