apiVersion: apps/v1
kind: Deployment
metadata:
  name: emp-friendly-payment
  namespace: emp-friendly
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emp-friendly-payment
  template:
    metadata:
      labels:
        app: emp-friendly-payment
    spec:
      containers:
        - name: emp-friendly-payment
          image: marttp/emp-friendly-payment
          resources:
            limits:
              cpu: 200m
              memory: 512Mi
          ports:
            - containerPort: 8080
              name: payment
              protocol: TCP
          env:
            - name: POINT_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: emp-friendly-cm
                  key: POINT_SERVICE_URL
            - name: REDIS_OM_URL
              valueFrom:
                secretKeyRef:
                  name: redis-secrect
                  key: REDIS_OM_URL
---
apiVersion: v1
kind: Service
metadata:
  name: emp-friendly-payment
  namespace: emp-friendly
spec:
  ports:
    - name: emp-friendly-payment
      port: 50207
      protocol: TCP
      targetPort: 8080
  selector:
    app: emp-friendly-payment
  type: ClusterIP
