apiVersion: apps/v1
kind: Deployment
metadata:
  name: emp-friendly-rest-mgm
  namespace: emp-friendly
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emp-friendly-rest-mgm
  template:
    metadata:
      labels:
        app: emp-friendly-rest-mgm
    spec:
      containers:
        - name: emp-friendly-rest-mgm
          image: marttp/emp-friendly-rest-mgm
          resources:
            requests:
              cpu: 300m
              memory: 512Mi
            limits:
              cpu: 300m
              memory: 512Mi
          ports:
            - containerPort: 8000
              name: rest-mgm
              protocol: TCP
          env:
            - name: REDIS_OM_URL
              valueFrom:
                secretKeyRef:
                  name: redis-secrect
                  key: REDIS_OM_URL
