apiVersion: apps/v1
kind: Deployment
metadata:
  name: emp-friendly-rest-mgm
  namespace: emp-friendly
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emp-friendly-rest-mgm
  template:
    metadata:
      labels:
        app: emp-friendly-rest-mgm
    spec:
      containers:
        - name: emp-friendly-rest-mgm
          image: marttp/emp-friendly-rest-mgm
          resources:
            limits:
              cpu: 200m
              memory: 512Mi
          ports:
            - containerPort: 8000
              name: rest-mgm
              protocol: TCP
          env:
            - name: CREATE_NEW_RESTAURANT_TOPIC_NAME
              valueFrom:
                configMapKeyRef:
                  name: emp-friendly-cm
                  key: CREATE_NEW_RESTAURANT_TOPIC_NAME
            - name: REDIS_OM_URL
              valueFrom:
                secretKeyRef:
                  name: redis-secrect
                  key: REDIS_OM_URL
---
apiVersion: v1
kind: Service
metadata:
  name: emp-friendly-rest-mgm
  namespace: emp-friendly
spec:
  ports:
    - name: emp-friendly-rest-mgm
      port: 50210
      protocol: TCP
      targetPort: 8000
  selector:
    app: emp-friendly-rest-mgm
  type: ClusterIP